Added delete functions to LFS
luxonis/luxonis-ml pull request #52
Opened 2023-12-19 10:07 UTC by DrejcPesjak

Added (and tested) 3 methods to LuxonisFileSystem:
 - delete_file
 - delete_files
 - delete_dir

Motivation was the Robothub DataIngestion Airflow pipeline, where we download and filter images from RH, and need a cleanup afterwards (deleting tmp files).

2023-12-19 14:51 UTC, kozlov721 requested changes
Would be better to raise a `NotImplementedError` when `self.is_fsspec` is `False`.

2023-12-19 15:11 UTC, conorsim requested changes
Looks good but I would request to quickly add `ThreadPoolExecutor` to the `delete_files` method

2023-12-21 18:04 UTC, conorsim approved these changes

2023-12-21 18:15 UTC, kozlov721 approved these changes
LGTM

2023-12-27 08:27 UTC, merged